# Generated by Django 3.2 on 2021-05-07 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0004_conversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='conversations',
            field=models.ManyToManyField(to='messenger.Conversation'),
        ),
    ]
