# Generated by Django 3.2 on 2021-05-07 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0005_profile_conversations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='start_conversation',
            field=models.DateTimeField(blank=True),
        ),
    ]
