# Generated by Django 3.2 on 2021-05-08 13:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messenger', '0006_alter_conversation_start_conversation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='start_conversation',
            field=models.DateTimeField(),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='firends',
        ),
        migrations.AddField(
            model_name='profile',
            name='firends',
            field=models.ManyToManyField(related_name='friends', to=settings.AUTH_USER_MODEL),
        ),
    ]
