# Generated by Django 3.2 on 2021-05-08 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0007_auto_20210508_1556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='firends',
            new_name='friends',
        ),
    ]
